export const ActionTypes = {
  //BOOK ACTIONS
  GET_BOOKS: "GET_BOOKS",
  SELECTED_BOOK: "SELECTED_BOOK",
  RESET_BOOK: "RESET_BOOK",

  //USER ACTIONS
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
};
